language: ruby
rvm:
- 1.9.3 
- 2.2.3
before_script: bundle exec rake db:migrate RAILS_ENV=test
before_install: gem update bundler
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
sudo: false
